<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>BrightScript Language File</string>
	<key>fileTypes</key>
	<array>
		<string>brs</string>
		<string>bas</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)^\s*(sub|if|f(or( each)?|unction)|while)\s*([a-zA-Z_]\w*)\s*(\(.*\)\s*)?$</string>
	<key>foldingStopMarker</key>
	<string>(?i)^\s*(next|e(nd(if| (sub|if|function))|xit( while)?))\s*$</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>BrightScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#program_statements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support_functions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage_types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant_numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.brightscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(').*$\n?</string>
			<key>name</key>
			<string>comment.line.apostrophe.brightscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.brightscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*?(?i:rem\s).*$\n?</string>
			<key>name</key>
			<string>comment.line.rem.brightscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.brightscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.brightscript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_roku_builtin</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>class</key>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>meta.class.brightscript</string>
		</dict>
		<key>class_roku_builtin</key>
		<dict>
			<key>match</key>
			<string>(?i:\bro(R(ss(Parser|Article)|e(sourceManager|ctangle|ad(File|WriteFile)|gistry(Section)?))|G(pio(Button|ControlPort)|lobal)|XML(Element|List)|MessagePort|B(yteArray|oolean|r(Sub|ightPackage))|S(ystemTime|t(orageInfo|ring( )?)|erialPort( )?)|NetworkConfiguration|C(ontrol(Down( )?|Up|Port)|ecInterface|lockWidget|reateFile)|T(imer|ouchScreen( )?|ext(Field|Widget))|I(RRemote( )?|n(t|valid)|mage(Player|Widget))|D(eviceInfo( )?|at(eTime|agram(Receiver|Sender)))|Url(Transfer|Event)|Video(Mode|Input|Player|Event)|Keyboard(Press( )?| )?|Quadravox(Button( )?|SNS5( )?)|Float|List|A(ssociativeArray|udio(Player|Event)|ppendFile|rray))\b)</string>
			<key>name</key>
			<string>support.class.brightscript</string>
		</dict>
		<key>constant_numeric</key>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.brightscript</string>
		</dict>
		<key>functions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.brightscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.brightscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.brightscript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.brightscript</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.brightscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((?i:function|sub))\s*([a-zA-Z_]\w*)\s*(\()([^)]*)(\)).*\n?</string>
			<key>name</key>
			<string>meta.function.brightscript</string>
		</dict>
		<key>literals</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(N(othing|ull)|True|Invalid|Empty|False)\b)</string>
			<key>name</key>
			<string>constant.language.brightscript</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>=|&gt;=|&lt;zz|&gt;|&lt;|&lt;&gt;|\+|-|\*|\/|\^|&amp;|\b(?i:(And|Not|Or))\b</string>
			<key>name</key>
			<string>keyword.operator.brightscript</string>
		</dict>
		<key>program_statements</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(s(t(op|ep)|ub)|i(n|f)|t(hen|o)|dim|print|e(nd(if| (sub|f(or|unction)|while))?|lse(if)?|xit (for|while))|f(or( each)?|unction)|as|while|re(turn|m)|goto)?\b)</string>
			<key>name</key>
			<string>keyword.control.brightscript</string>
		</dict>
		<key>storage_types</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(string|in(te(rface|ger)|valid)|object|double|float|b(oolean|rsub))\b)</string>
			<key>name</key>
			<string>storage.type.brightscript</string>
		</dict>
		<key>support_builtin_functions</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(GetLastRun(RuntimeError|CompileError)|R(nd|un)|Box|Type)\b)</string>
			<key>name</key>
			<string>support.function.brightscript</string>
		</dict>
		<key>support_functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#support_builtin_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support_global_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support_global_string_functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support_global_math_functions</string>
				</dict>
			</array>
		</dict>
		<key>support_global_functions</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(Re(adAsciiFile|bootSystem)|GetInterface|MatchFiles|Sleep|C(opyFile|reate(Directory|Object))|Delete(Directory|File)|UpTime|FormatDrive|ListDir|W(ait|riteAsciiFile))\b)</string>
			<key>name</key>
			<string>support.function.brightscript</string>
		</dict>
		<key>support_global_math_functions</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(S(in|qr|gn)|C(sng|dbl|os)|Tan|Int|Exp|Fix|Log|A(tn|bs))\b)</string>
			<key>name</key>
			<string>support.function.brightscript</string>
		</dict>
		<key>support_global_string_functions</key>
		<dict>
			<key>match</key>
			<string>(?i:\b(Right|Mid|Str(i(ng(i)?)?)?|Chr|Instr|UCase|Val|Asc|L(Case|e(n|ft)))\b)</string>
			<key>name</key>
			<string>support.function.brightscript</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.brightscript</string>
	<key>uuid</key>
	<string>291022B4-6B1D-11D9-90EB-000D93589AF6</string>
</dict>
</plist>
